{% set name = "doebase" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pablocarb/doebase/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 530f1d0e11a5ca3f461be1be2fd8e1c041207b9f0d44dc1acd0ca8f034b91e0d

build:
  number: 2
  script: {{ PYTHON }} -m pip install -vv .
  skip: true  # [win or py != 37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - scipy
    - requests
    - scikit-learn
    - pysbol2

test:
  source_files:
    - tests
  imports:
    - doebase
  requires:
    - pytest
  commands:
    - python -m pytest

about:
  home: https://github.com/pablocarb/doebase/
  summary: An optimal Design of Experiments (DoE) base package for synthetic biology
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
